24/footer
Melrt/training_front pull request #2
Opened 2021-09-06 14:36 UTC by Melrt

https://trello.com/c/OFuEiNh1/24-f-2-cas-pratique-cr%C3%A9er-le-footer

J'ai mis un fixed-bottom provisoire le temps d'avoir du contenue dans ma page.
Et j'ai pas trouvé comment gérer les doublons dans le fichier application.fr.yml, j'ai regardé sur d'autre repos mais j'ai pas trouvé de solutions.

2021-09-06 15:57 UTC, CapSens-SM requested changes

2021-09-06 15:57 UTC, CapSens-SM commented on app/views/layouts/application/_footer.html.erb
> +          <p><%= t('address_brand') %><br> <%= t('zipcode_brand') %> <%= t('paris') %></p>
Garde des clés agnostiques de la valeur qu'elles peuvent contenir. Si le client déménage à bruxelles, on veut pas avoir besoin de changer la clé, juste la valeur.

2021-09-06 15:57 UTC, CapSens-SM commented on config/locales/views/layouts/application.fr.yml
> +  credit_application_form: Formulaire de demande de crédit
le premier ancêtre commun c'est `layouts.application` pas la racine

2021-09-06 15:57 UTC, CapSens-SM commented on app/views/layouts/application/_footer.html.erb
> +          <p><%= t('address_brand') %><br> <%= t('zipcode_brand') %> <%= t('paris') %></p>
Privilégie un content_tag pour ce genre de truc pour avoir quelque chose de plus clean (moins de `<%=` `%>`)

2021-09-06 16:12 UTC, CapSens-SM requested changes

2021-09-06 16:12 UTC, CapSens-SM commented on app/views/layouts/application/_footer.html.erb
> +          <li><a class="text-decoration-none" href="#"><%= t('credit_application_form') %></a></li>
Pour les liens, utilise sytématiquement un  
```
<%= link_to  t('home'), '#',  class: 'text-decoration-none' %>
```

2021-09-06 16:12 UTC, CapSens-SM commented on app/views/layouts/application/_footer.html.erb
> +        <h3 class="fw-bold text-uppercase"><%= t('.discover') %></h3>
Quand t'as une balise simple ou fermante qui contient du i18n, c'et plus propre d'utiliser un tag ou un content_tag. 
```
        <%= content_tag :h3, t('.discover'), class: 'fw-bold text-uppercase' %>
```

2021-09-07 06:46 UTC, Melrt commented on config/locales/views/layouts/application.fr.yml
> +  credit_application_form: Formulaire de demande de crédit
Ca ne fonctionne que dans la racine 
Quand je retire le point devant home les logs mettent ce chemin `[i18n-debug] fr.home => nil`

2021-09-07 06:59 UTC, Melrt commented on app/views/layouts/application/_footer.html.erb
> +          <p><%= t('address_brand') %><br> <%= t('zipcode_brand') %> <%= t('paris') %></p>
C'est possible de faire un content_tag avec 3 éléments ? t('address_brand'), t('zipcode_brand') et t('city_brand') ?
Je vois pas comment faire ca

2021-09-07 07:01 UTC, CapSens-SM commented on config/locales/views/layouts/application.fr.yml
> +  credit_application_form: Formulaire de demande de crédit
Oui. Tu peux namespacer ta clé : 

`I18n.t :home, scope: %i[activerecord errors messages]`

2021-09-07 07:31 UTC, CapSens-SM commented on app/views/layouts/application/_footer.html.erb
> +          <p><%= t('address_brand') %><br> <%= t('zipcode_brand') %> <%= t('paris') %></p>
Tu as plusieurs solutions : 

```
<%= content_tag :p, [t('address_brand'), tag(:br), t('zipcode_brand'), t('city_brand')].join("\n").html_safe %>
```

ou 

```
<%= content_tag :p, "Hello <br /> You".html_safe %>
```

ou encore 

```
<%= content_tag :p, t('brand_full_address_html) %>
```

qui contiendrait directement une concaténation des 3 clés et du html interne : 

> "35 rue beaubourg <br /> 75003 PARIS"

2021-09-07 07:32 UTC, CapSens-SM commented on app/views/layouts/application/_footer.html.erb
> +          <p><%= t('address_brand') %><br> <%= t('zipcode_brand') %> <%= t('paris') %></p>
D'ailleurs ce serait pas mal d'inverser les clés : plutot que `city_brand`  =>  `brand_city`

2021-09-07 08:15 UTC, CapSens-SM approved these changes

2021-09-07 08:15 UTC, CapSens-SM commented on app/views/layouts/application/_footer.html.erb
> +          <li><%= link_to  (I18n.t :home, scope: %i[layouts application]), '#',  class: 'text-decoration-none' %></li>
Pas besoin de parenthèse ici, si tu veux une parenthèse, met la plutot sur I18n.t : 

```
<li>
  <%= link_to I18n.t(:home, scope: %i[layouts application]), '#', class: 'text-decoration-none' %>
</li>
```

2021-09-07 08:15 UTC, CapSens-SM commented on app/views/layouts/application/_footer.html.erb
> +          <li><%= link_to (I18n.t :credit_application_form, scope: %i[layouts application]), '#', class: 'text-decoration-none' %></li>
idem + attention aux doubles / triples espaces superflus

2021-09-07 08:15 UTC, CapSens-SM commented on app/views/layouts/application/_footer.html.erb
> +        <%= image_tag "logo_capsens", alt: "alttext", class: "mx-3", width: 150 %>
Pour la formation on s'en fiche, mais à l'avenir, le alt devra aussi passer par i18n et mieux vaut metre une string vide que "alttext". L'idée est de décrie rapidement l'image pour les aveugles mais aussi pour booster le SEO de la page en permettant à Google d'indexer l'image si elle est publique

2021-09-07 08:21 UTC, Melrt commented on app/views/layouts/application/_footer.html.erb
> +        <%= image_tag "logo_capsens", alt: "alttext", class: "mx-3", width: 150 %>
Ca roule je note pour la prochaine fois

2021-09-07 08:23 UTC, merged